alias: Milkman - Take bottles out the bottles notification

trigger:

  # Trigger at 19:00 the night before milk day
  - platform: template
    value_template: "{{ as_timestamp(now()) > (as_timestamp(state_attr('calendar.house_milkman','start_time')) - 18000) }}"

  # Trigger every 20 minutes
  - platform: time_pattern
    minutes: "/20"

condition:
  condition: and
  conditions:

    # only trigger the day before milk day
    - condition: template
      value_template: "{{ as_timestamp(now()) > (as_timestamp(state_attr('calendar.house_milkman','start_time')) - 86400) }}"

    # only trigger the night before milk day
    - condition: time
      after: '17:59:59'
      before: '12:00:00'

    # only trigger if the milk bottle holder has not been placed on the doorstep
    - condition: state
      entity_id: binary_sensor.milk_bottle_contact
      state: 'on'

    # only send a notication once every 30 minutes
    - condition: template
      value_template: "{{ (as_timestamp(states.sensor.date_time.last_changed) - (as_timestamp(state_attr('automation.milkman_take_bottles_out_the_bottles_notification','last_triggered')))) > 1800 }}"

action:

  - service: notify.ios_james_iphone
    data_template:
      title: 🥛 Milkman
      message: "The milk crate needs to be taken outside."
