alias: "Back Garden - Outhouse light"

trigger:

  - platform: state
    entity_id: binary_sensor.outhouse_door_contact

action:

  - service_template: >
      {% if is_state('binary_sensor.outhouse_door_contact','on') %}
        light.turn_on
      {% elif is_state('binary_sensor.outhouse_door_contact','off') %}
        light.turn_off
      {% endif %}
    data:
      entity_id: light.outhouse_light
